### ISSUE TITLE
Referral 

### ISSUE THREAD

**Issue by Alexia-iordanoglou** [voucherifyio/commerce-tools-integration#146]
Hi, does the extension support Referral campaigns as well? 

It was not mentioned in the list specifically
<img width="710" alt="Screenshot 2023-03-09 at 12 30 06" src="https://user-images.githubusercontent.com/54448512/224010527-6f433595-d121-48c9-8a01-02755f541633.png">

thanks

**Comment by p-zielinski** [comment]
Sorry for the delay. Yes we do support Referral campaigns as well.
[https://youtu.be/f6hFUtV0n1k?t=479](https://youtu.be/f6hFUtV0n1k?t=479)
